import { MaterialPalette, MaterialText, MaterialTypography, TextField, Vertical } from "@material";
import { ChoreoInfo } from "../../ui/choreo_info.slint";
import { ChoreographySettings } from "choreography_settings.slint";
import { Date, DatePickerPopup } from "std-widgets.slint";
import { Translations } from "../../ui/translations.slint";

export component ChoreographySettingsChoreographyCard inherits Rectangle {
    in-out property <Date> date: ChoreoInfo.choreo_date;

    background: MaterialPalette.surface_container;
    border-width: 1px;
    border-color: MaterialPalette.outline_variant;
    border-radius: 8px;

    Vertical {
        padding: 12px;
        spacing: 8px;

        MaterialText {
            text: Translations.choreography_section_title;
            font-size: MaterialTypography.title_large.font_size;
            font-weight: MaterialTypography.title_large.font_weight;
        }

        TextField {
            label: Translations.choreography_comment_placeholder;
            text: ChoreoInfo.choreo_comment;
            edited(value) => { ChoreographySettings.update_comment(value); }
        }

        TextField {
            label: Translations.choreography_name_placeholder;
            text: ChoreoInfo.choreo_name;
            edited(value) => { ChoreographySettings.update_name(value); }
        }

        TextField {
            label: Translations.choreography_subtitle_placeholder;
            text: ChoreoInfo.choreo_subtitle;
            edited(value) => { ChoreographySettings.update_subtitle(value); }
        }

        TextField {
            label: Translations.choreography_date_label;
            read_only: true;
            text: root.date.year + "-" + root.date.month + "-" + root.date.day;
            trailing_icon: @image-url("../../ui/icons/CalendarToday.svg");
            trailing_icon_clicked => { date_picker.show(); }
        }

        TextField {
            label: Translations.choreography_variation_placeholder;
            text: ChoreoInfo.choreo_variation;
            edited(value) => { ChoreographySettings.update_variation(value); }
        }

        TextField {
            label: Translations.choreography_author_placeholder;
            text: ChoreoInfo.choreo_author;
            edited(value) => { ChoreographySettings.update_author(value); }
        }

        TextField {
            label: Translations.choreography_description_placeholder;
            text: ChoreoInfo.choreo_description;
            edited(value) => { ChoreographySettings.update_description(value); }
        }
    }

    date_picker := DatePickerPopup {
        title: Translations.choreography_date_picker_title;
        date <=> root.date;

        accepted(date) => {
            root.date = date;
            ChoreographySettings.update_date_parts(date.year, date.month, date.day);
            date_picker.close();
        }
    }
}
