import { CheckBoxTile, CheckState, MaterialPalette, MaterialText, MaterialTypography, Vertical } from "@material";
import { ChoreographySettings } from "choreography_settings.slint";
import { Translations } from "../../ui/translations.slint";

export component ChoreographySettingsDisplayCard inherits Rectangle {
    background: MaterialPalette.surface_container;
    border-width: 1px;
    border-color: MaterialPalette.outline_variant;
    border-radius: 8px;

    Vertical {
        padding: 12px;
        spacing: 8px;

        MaterialText {
            text: Translations.choreography_display_title;
            font-size: MaterialTypography.title_large.font_size;
            font-weight: MaterialTypography.title_large.font_weight;
        }

        CheckBoxTile {
            text: Translations.choreography_draw_path_from_label;
            check_state: ChoreographySettings.draw_path_from ? CheckState.checked : CheckState.unchecked;
            checked_state_changed(state) => {
                ChoreographySettings.update_draw_path_from(state == CheckState.checked);
            }
        }

        CheckBoxTile {
            text: Translations.choreography_draw_path_to_label;
            check_state: ChoreographySettings.draw_path_to ? CheckState.checked : CheckState.unchecked;
            checked_state_changed(state) => {
                ChoreographySettings.update_draw_path_to(state == CheckState.checked);
            }
        }

        CheckBoxTile {
            text: Translations.choreography_show_timestamps_label;
            check_state: ChoreographySettings.show_timestamps ? CheckState.checked : CheckState.unchecked;
            checked_state_changed(state) => {
                ChoreographySettings.update_show_timestamps(state == CheckState.checked);
            }
        }

        CheckBoxTile {
            text: Translations.choreography_positions_at_side_label;
            check_state: ChoreographySettings.positions_at_side ? CheckState.checked : CheckState.unchecked;
            checked_state_changed(state) => {
                ChoreographySettings.update_positions_at_side(state == CheckState.checked);
            }
        }

        CheckBoxTile {
            text: Translations.choreography_show_legend_label;
            check_state: ChoreographySettings.show_legend ? CheckState.checked : CheckState.unchecked;
            checked_state_changed(state) => {
                ChoreographySettings.update_show_legend(state == CheckState.checked);
            }
        }
    }
}
