import { MaterialPalette, Vertical } from "@material";
import { ChoreographySettingsChoreographyCard } from "choreography_settings_choreography_card.slint";
import { ChoreographySettingsDisplayCard } from "choreography_settings_display_card.slint";
import { ChoreographySettingsFloorCard } from "choreography_settings_floor_card.slint";
import { ChoreographySettingsSceneCard } from "choreography_settings_scene_card.slint";

export component ChoreographySettingsView inherits Rectangle {
    background: MaterialPalette.surface_variant;
    preferred-height: content.preferred-height;
    height: self.preferred-height;

    content := Vertical {
        width: parent.width;
        height: parent.height;
        padding: 8px;
        spacing: 12px;

        ChoreographySettingsSceneCard {}
        ChoreographySettingsDisplayCard {}
        ChoreographySettingsChoreographyCard {}
        ChoreographySettingsFloorCard {}
    }
}
