import { Horizontal, IconButton, MaterialPalette, MaterialText, MaterialTypography, Slider } from "@material";
import { SliderWithTicks } from "slider_with_ticks.slint";

export component AudioPlayerView inherits Rectangle {
    in property <float> speed;
    in property <float> minimum_speed;
    in property <float> maximum_speed;
    in property <float> position;
    in property <float> duration;
    in property <[float]> tick_values;
    in property <bool> can_seek;
    in property <bool> can_link_scene_to_position;
    in property <bool> is_playing;
    in property <string> speed_label;
    in property <string> duration_label;

    callback speed_changed(float);
    callback position_changed(float);
    callback position_drag_started();
    callback position_drag_completed();
    callback link_scene_to_position();
    callback toggle_play_pause();

    background: MaterialPalette.surface_container_low;
    border-width: 1px;
    border-color: MaterialPalette.outline;
    border-radius: 8px;

    content := Horizontal {
        width: parent.width;
        height: parent.height;
        padding: 12px;
        spacing: 12px;

        Slider {
            minimum: minimum_speed;
            maximum: maximum_speed;
            value: speed;
            width: 240px;
            value_changed(value) => { speed_changed(value); }
        }

        MaterialText {
            text: speed_label;
            color: MaterialPalette.on_surface_variant;
            font-size: MaterialTypography.label_large.font_size;
            font-weight: MaterialTypography.label_large.font_weight;
            horizontal-alignment: right;
            vertical-alignment: center;
        }

        SliderWithTicks {
            minimum: 0;
            maximum: duration;
            value: position;
            enabled: can_seek;
            value_changed(value) => { position_changed(value); }
            drag_started => { position_drag_started(); }
            drag_completed => { position_drag_completed(); }
            tick_values: tick_values;
        }

        MaterialText {
            text: duration_label;
            color: MaterialPalette.on_surface_variant;
            font-size: MaterialTypography.label_large.font_size;
            font-weight: MaterialTypography.label_large.font_weight;
            width: 64px;
            vertical-alignment: center;
        }

        IconButton {
            icon: @image-url("icons/Link.svg");
            enabled: can_link_scene_to_position;
            clicked => { link_scene_to_position(); }
        }

        IconButton {
            icon: is_playing ? @image-url("icons/Pause.svg") : @image-url("icons/Play.svg");
            clicked => { toggle_play_pause(); }
        }
    }
}
