import { Date } from "std-widgets.slint";

// information about the current choreography
export global ChoreoInfo {
    in-out property <string> choreo_name: "Lorem ipsum dolor sit amet";
    in-out property <string> choreo_subtitle: "consectetur adipiscing elit";
    in-out property <string> choreo_comment: "";
    in-out property <Date> choreo_date;
    in-out property <string> choreo_variation: "";
    in-out property <string> choreo_author: "";
    in-out property <string> choreo_description: "";
    in-out property <float> choreo_transparency: 0.0;
}
