import { IconButton, ListView, MaterialPalette, MaterialText, Vertical, Horizontal } from "@material";
import { SceneItemView } from "scene_item_view.slint";
import { SceneSearchBar } from "scene_search_bar.slint";
import { Translations } from "translations.slint";

export struct SceneListItem {
    name: string,
    timestamp_text: string,
    color: color,
    is_selected: bool,
}

export component ScenesPaneView inherits Rectangle {
    in property <[SceneListItem]> scenes;
    in-out property <string> search_text;
    in property <bool> show_timestamps;
    in property <bool> can_save_choreo;
    in property <bool> can_delete_scene;
    in property <bool> can_navigate_to_settings;
    in property <bool> can_navigate_to_dancer_settings;

    callback select_scene(int);
    callback update_search_text(string);
    callback add_scene_before();
    callback add_scene_after();
    callback delete_scene();
    callback open_choreo();
    callback save_choreo();
    callback navigate_to_settings();
    callback navigate_to_dancer_settings();

    background: MaterialPalette.surface;

    content := Vertical {
        width: parent.width;
        height: parent.height;
        padding: 12px;
        spacing: 12px;

        Rectangle {
            background: MaterialPalette.surface_container;
            border-radius: 12px;
            vertical-stretch: 1;

            Vertical {
                width: parent.width;
                height: parent.height;
                padding: 8px;

                ListView {
                    vertical-stretch: 1;
                    for scene[index] in scenes: Rectangle {
                        background: transparent;
                        height: root.show_timestamps ? 62px : 50px;

                        scene_content := SceneItemView {
                            width: parent.width;
                            height: parent.height - 8px;
                            y: 4px;
                            scene_name: scene.name;
                            timestamp_text: scene.timestamp_text;
                            scene_color: scene.color;
                            show_timestamps: root.show_timestamps;
                            is_selected: scene.is_selected;
                            select_scene => { root.select_scene(index); }
                        }
                    }
                }
            }
        }

        SceneSearchBar {
            placeholder_text: Translations.search_placeholder;
            text <=> search_text;
            edited(value) => { update_search_text(value); }
        }

        Horizontal {
            spacing: 8px;

            IconButton {
                icon: @image-url("icons/TableRowPlusBefore.svg");
                tooltip: Translations.scenes_add_before;
                clicked => { add_scene_before(); }
            }
            IconButton {
                icon: @image-url("icons/TableRowPlusAfter.svg");
                tooltip: Translations.scenes_add_after;
                clicked => { add_scene_after(); }
            }
            IconButton {
                icon: @image-url("icons/Delete.svg");
                tooltip: Translations.delete_scene_dialog_title;
                enabled: can_delete_scene;
                clicked => { delete_scene(); }
            }
        }

        Horizontal {
            spacing: 8px;
            IconButton {
                icon: @image-url("icons/FolderOpen.svg");
                tooltip: Translations.scenes_open;
                clicked => { open_choreo(); }
            }
            IconButton {
                icon: @image-url("icons/ContentSave.svg");
                tooltip: Translations.scenes_save;
                enabled: can_save_choreo;
                clicked => { save_choreo(); }
            }
            IconButton {
                icon: @image-url("icons/Cog.svg");
                tooltip: Translations.settings_title;
                enabled: can_navigate_to_settings;
                clicked => { navigate_to_settings(); }
            }
            IconButton {
                icon: @image-url("icons/AccountGroup.svg");
                tooltip: Translations.dancers_title;
                enabled: can_navigate_to_dancer_settings;
                clicked => { navigate_to_dancer_settings(); }
            }
        }
    }
}
