import { DropDownMenu, IconButton, MaterialPalette, MaterialText, MaterialTypography, MenuItem, ScrollView, Switch, Vertical, Horizontal } from "@material";
import { Palette } from "std-widgets.slint";
import { ColorPicker } from "color_picker.slint";
import { Translations } from "translations.slint";

export component SettingsPage inherits Rectangle {
    in property <string> title_text: Translations.settings_title;
    in property <string> use_system_theme_text: Translations.settings_use_system_theme_label;
    in property <string> dark_mode_text: Translations.dark_mode_label;
    in property <string> primary_color_text: Translations.settings_primary_color_label;
    in property <string> secondary_color_text: Translations.settings_secondary_color_label;
    in property <string> tertiary_color_text: Translations.settings_tertiary_color_label;
    in property <string> audio_backend_text: Translations.settings_audio_backend_label;
    in property <string> audio_backend_rodio_text: Translations.settings_audio_backend_rodio_label;
    in property <string> audio_backend_awedio_text: Translations.settings_audio_backend_awedio_label;
    property <[MenuItem]> audio_backend_items: [
        {
            icon: @image-url(""),
            text: root.audio_backend_rodio_text,
            trailing_text: "",
            enabled: true,
            text_color: Palette.foreground,
        },
        {
            icon: @image-url(""),
            text: root.audio_backend_awedio_text,
            trailing_text: "",
            enabled: true,
            text_color: Palette.foreground,
        },
    ];

    in property <bool> use_system_theme;
    in property <bool> can_use_system_theme: true;
    in property <bool> is_dark_mode;
    in property <bool> use_primary_color;
    in property <bool> use_secondary_color;
    in property <bool> use_tertiary_color;

    in property <color> primary_color;
    in property <color> secondary_color;
    in property <color> tertiary_color;
    in property <int> selected_audio_backend_index: 0;

    callback update_use_system_theme(bool);
    callback update_is_dark_mode(bool);
    callback update_use_primary_color(bool);
    callback update_use_secondary_color(bool);
    callback update_use_tertiary_color(bool);
    callback update_primary_color(color);
    callback update_secondary_color(color);
    callback update_tertiary_color(color);
    callback update_audio_backend(int);
    callback navigate_back();

    background: MaterialPalette.surface_container_low;

    ScrollView {
        Vertical {
            padding: 24px;
            spacing: 12px;

            Horizontal {
                spacing: 8px;

                IconButton {
                    icon: @image-url("icons/ArrowLeft.svg");
                    tooltip: title_text;
                    clicked => { navigate_back(); }
                }

                MaterialText {
                    text: title_text;
                    font-size: MaterialTypography.headline_small.font_size;
                    font-weight: MaterialTypography.headline_small.font_weight;
                }
            }

            Rectangle {
                visible: can_use_system_theme;
                background: MaterialPalette.surface_container;
                border-width: 1px;
                border-color: MaterialPalette.outline_variant;
                border-radius: 8px;

                Vertical {
                    padding: 12px;
                    spacing: 8px;

                    Horizontal {
                        spacing: 12px;

                        MaterialText {
                            text: use_system_theme_text;
                            horizontal-stretch: 1;
                            font-size: MaterialTypography.body_medium.font_size;
                            font-weight: MaterialTypography.body_medium.font_weight;
                        }
                        Switch {
                            horizontal-stretch: 0;
                            width: 108px;
                            height: 48px;
                            checked: use_system_theme;
                            checked_state_changed(value) => { update_use_system_theme(value); }
                        }
                    }

                }
            }

            Rectangle {
                background: MaterialPalette.surface_container;
                border-width: 1px;
                border-color: MaterialPalette.outline_variant;
                border-radius: 8px;

                Vertical {
                    padding: 12px;
                    spacing: 8px;

                    MaterialText {
                        text: audio_backend_text;
                        font-size: MaterialTypography.body_medium.font_size;
                        font-weight: MaterialTypography.body_medium.font_weight;
                    }

                    DropDownMenu {
                        enabled: true;
                        items: root.audio_backend_items;
                        current_index: root.selected_audio_backend_index;
                        selected(index) => { root.update_audio_backend(index); }
                    }
                }
            }

            Rectangle {
                background: MaterialPalette.surface_container;
                border-width: 1px;
                border-color: MaterialPalette.outline_variant;
                border-radius: 8px;

                Vertical {
                    padding: 12px;
                    spacing: 8px;

                    Horizontal {
                        spacing: 12px;

                        MaterialText {
                            text: dark_mode_text;
                            horizontal-stretch: 1;
                            font-size: MaterialTypography.body_medium.font_size;
                            font-weight: MaterialTypography.body_medium.font_weight;
                        }
                        Switch {
                            horizontal-stretch: 0;
                            width: 108px;
                            height: 48px;
                            enabled: can_use_system_theme ? !use_system_theme : true;
                            checked: is_dark_mode;
                            checked_state_changed(value) => { update_is_dark_mode(value); }
                        }
                    }

                    Horizontal {
                        spacing: 12px;

                        MaterialText {
                            text: primary_color_text;
                            horizontal-stretch: 1;
                            font-size: MaterialTypography.body_medium.font_size;
                            font-weight: MaterialTypography.body_medium.font_weight;
                        }
                        Switch {
                            horizontal-stretch: 0;
                            width: 108px;
                            height: 48px;
                            checked: use_primary_color;
                            checked_state_changed(value) => { update_use_primary_color(value); }
                        }
                    }

                    Horizontal {
                        spacing: 12px;

                        Rectangle {
                            width: 108px;
                            height: 36px;
                            border-radius: 6px;
                            background: primary_color;
                        }
                        ColorPicker {
                            horizontal-stretch: 1;
                            opacity: use_primary_color ? 1.0 : 0.45;
                            selected_color: primary_color;
                            color_changed(value) => {
                                if (root.use_primary_color) {
                                    update_primary_color(value);
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: MaterialPalette.surface_container;
                border-width: 1px;
                border-color: MaterialPalette.outline_variant;
                border-radius: 8px;

                Vertical {
                    padding: 12px;
                    spacing: 8px;

                    Horizontal {
                        spacing: 12px;

                        MaterialText {
                            text: secondary_color_text;
                            horizontal-stretch: 1;
                            font-size: MaterialTypography.body_medium.font_size;
                            font-weight: MaterialTypography.body_medium.font_weight;
                        }
                        Switch {
                            horizontal-stretch: 0;
                            width: 108px;
                            height: 48px;
                            enabled: use_primary_color;
                            checked: use_secondary_color;
                            checked_state_changed(value) => { update_use_secondary_color(value); }
                        }
                    }

                    Horizontal {
                        spacing: 12px;

                        Rectangle {
                            width: 108px;
                            height: 36px;
                            border-radius: 6px;
                            background: secondary_color;
                        }
                        ColorPicker {
                            horizontal-stretch: 1;
                            opacity: use_secondary_color ? 1.0 : 0.45;
                            selected_color: secondary_color;
                            color_changed(value) => {
                                if (root.use_secondary_color) {
                                    update_secondary_color(value);
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: MaterialPalette.surface_container;
                border-width: 1px;
                border-color: MaterialPalette.outline_variant;
                border-radius: 8px;

                Vertical {
                    padding: 12px;
                    spacing: 8px;

                    Horizontal {
                        spacing: 12px;

                        MaterialText {
                            text: tertiary_color_text;
                            horizontal-stretch: 1;
                            font-size: MaterialTypography.body_medium.font_size;
                            font-weight: MaterialTypography.body_medium.font_weight;
                        }
                        Switch {
                            horizontal-stretch: 0;
                            width: 108px;
                            height: 48px;
                            enabled: use_secondary_color;
                            checked: use_tertiary_color;
                            checked_state_changed(value) => { update_use_tertiary_color(value); }
                        }
                    }

                    Horizontal {
                        spacing: 12px;

                        Rectangle {
                            width: 108px;
                            height: 36px;
                            border-radius: 6px;
                            background: tertiary_color;
                        }
                        ColorPicker {
                            horizontal-stretch: 1;
                            opacity: use_tertiary_color ? 1.0 : 0.45;
                            selected_color: tertiary_color;
                            color_changed(value) => {
                                if (root.use_tertiary_color) {
                                    update_tertiary_color(value);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
