import { MaterialPalette, MaterialWindow, MenuItem } from "@material";
import { MainPage } from "main_page.slint";
import { DancerSettingsPage } from "dancer_settings_page.slint";
import { SettingsPage } from "../src/settings/settings_page.slint";
import { SettingsInfo } from "../src/settings/settings_info.slint";
import { DancerListItem } from "dancers_pane_view.slint";
import { Palette } from "std-widgets.slint";
import { Translations } from "translations.slint";

export component ShellHost inherits MaterialWindow {
    in property <string> title_text: Translations.app_title;
    in property <int> content_index: 0;
    in-out property <int> selected_mode_index: -1;
    in property <bool> is_mode_selection_enabled: true;
    in-out property <length> nav_width: 0px;
    in-out property <bool> is_nav_open: false;
    in-out property <bool> is_choreography_settings_open: false;
    in-out property <bool> is_audio_player_open: false;
    in-out property <bool> is_dialog_open: false;
    in property <string> dialog_content;
    in property <[DancerListItem]> dancer_settings_dancer_items: [];
    in property <int> dancer_settings_selected_dancer_index: -1;
    in property <bool> dancer_settings_can_delete_dancer: false;
    in property <bool> dancer_settings_can_swap_dancers: false;
    in property <[MenuItem]> dancer_settings_role_options: [];
    in property <[MenuItem]> dancer_settings_dancer_options: [];
    in property <int> dancer_settings_selected_role_index: -1;
    in property <int> dancer_settings_swap_from_index: -1;
    in property <int> dancer_settings_swap_to_index: -1;
    in property <string> dancer_settings_dancer_name: "";
    in property <string> dancer_settings_dancer_shortcut: "";
    in property <color> dancer_settings_dancer_color: MaterialPalette.primary;

    callback toggle_nav();
    callback close_nav();
    callback open_settings();
    callback close_settings();
    callback open_image();
    callback open_audio();
    callback reset_floor_viewport();
    callback select_mode(int);
    callback close_dialog();
    callback dancer_settings_cancel();
    callback dancer_settings_select_dancer(int);
    callback dancer_settings_add_dancer();
    callback dancer_settings_delete_dancer();
    callback dancer_settings_select_role(int);
    callback dancer_settings_update_dancer_name(string);
    callback dancer_settings_update_dancer_shortcut(string);
    callback dancer_settings_update_dancer_color(color);
    callback dancer_settings_update_swap_from(int);
    callback dancer_settings_update_swap_to(int);
    callback dancer_settings_swap();
    callback dancer_settings_save();
    callback floor_pointer_pressed(x: float, y: float, is_primary: bool, is_in_contact: bool);
    callback floor_pointer_moved(x: float, y: float, is_primary: bool, is_in_contact: bool);
    callback floor_pointer_released(x: float, y: float, is_primary: bool, is_in_contact: bool);
    callback floor_pointer_wheel_changed(
        delta_x: float,
        delta_y: float,
        x: float,
        y: float,
        control_modifier: bool
    );
    callback floor_redraw();

    private property <ColorScheme> effective_color_scheme:
        SettingsInfo.is_dark_mode ? ColorScheme.dark : ColorScheme.light;

    title: root.title_text;
    icon: @image-url("app_icon.svg");

    init => {
        Palette.color-scheme = root.effective_color_scheme;
    }

    changed effective_color_scheme => {
        Palette.color-scheme = root.effective_color_scheme;
    }

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: transparent;

        main_page := MainPage {
            visible: root.content_index == 0;
            selected_mode_index <=> root.selected_mode_index;
            is_mode_selection_enabled: root.is_mode_selection_enabled;
            is_nav_open <=> root.is_nav_open;
            is_choreography_settings_open <=> root.is_choreography_settings_open;
            is_audio_player_open <=> root.is_audio_player_open;
            is_dialog_open <=> root.is_dialog_open;
            dialog_content: root.dialog_content;

            toggle_nav => { root.toggle_nav(); }
            close_nav => { root.close_nav(); }
            open_settings => { root.open_settings(); }
            close_settings => { root.close_settings(); }
            open_image => { root.open_image(); }
            open_audio => { root.open_audio(); }
            reset_floor_viewport => { root.reset_floor_viewport(); }
            select_mode(index) => { root.select_mode(index); }
            close_dialog => { root.close_dialog(); }
            floor_pointer_pressed(x, y, is_primary, is_in_contact) => {
                root.floor_pointer_pressed(x, y, is_primary, is_in_contact);
            }
            floor_pointer_moved(x, y, is_primary, is_in_contact) => {
                root.floor_pointer_moved(x, y, is_primary, is_in_contact);
            }
            floor_pointer_released(x, y, is_primary, is_in_contact) => {
                root.floor_pointer_released(x, y, is_primary, is_in_contact);
            }
            floor_pointer_wheel_changed(delta_x, delta_y, x, y, control_modifier) => {
                root.floor_pointer_wheel_changed(
                    delta_x,
                    delta_y,
                    x,
                    y,
                    control_modifier
                );
            }
            floor_redraw => {
                root.floor_redraw();
            }
        }
        settings_page := SettingsPage {
            visible: root.content_index == 1;
            can_use_system_theme: SettingsInfo.can_use_system_theme;
            use_system_theme: SettingsInfo.use_system_theme;
            is_dark_mode: SettingsInfo.is_dark_mode;
            use_primary_color: SettingsInfo.use_primary_color;
            use_secondary_color: SettingsInfo.use_secondary_color;
            use_tertiary_color: SettingsInfo.use_tertiary_color;
            primary_color: SettingsInfo.primary_color;
            secondary_color: SettingsInfo.secondary_color;
            tertiary_color: SettingsInfo.tertiary_color;
            selected_audio_backend_index: SettingsInfo.selected_audio_backend_index;

            update_use_system_theme(value) => { SettingsInfo.update_use_system_theme(value); }
            update_is_dark_mode(value) => { SettingsInfo.update_is_dark_mode(value); }
            update_use_primary_color(value) => { SettingsInfo.update_use_primary_color(value); }
            update_use_secondary_color(value) => { SettingsInfo.update_use_secondary_color(value); }
            update_use_tertiary_color(value) => { SettingsInfo.update_use_tertiary_color(value); }
            update_primary_color(value) => { SettingsInfo.update_primary_color(value); }
            update_secondary_color(value) => { SettingsInfo.update_secondary_color(value); }
            update_tertiary_color(value) => { SettingsInfo.update_tertiary_color(value); }
            update_audio_backend(index) => { SettingsInfo.update_audio_backend(index); }
            navigate_back => { SettingsInfo.navigate_back(); }
        }
        dancer_settings_page := DancerSettingsPage {
            visible: root.content_index == 2;
            dancer_items: root.dancer_settings_dancer_items;
            selected_dancer_index: root.dancer_settings_selected_dancer_index;
            can_delete_dancer: root.dancer_settings_can_delete_dancer;
            can_swap_dancers: root.dancer_settings_can_swap_dancers;
            role_options: root.dancer_settings_role_options;
            dancer_options: root.dancer_settings_dancer_options;
            selected_role_index: root.dancer_settings_selected_role_index;
            swap_from_index: root.dancer_settings_swap_from_index;
            swap_to_index: root.dancer_settings_swap_to_index;
            dancer_name: root.dancer_settings_dancer_name;
            dancer_shortcut: root.dancer_settings_dancer_shortcut;
            dancer_color: root.dancer_settings_dancer_color;
            cancel => { root.dancer_settings_cancel(); }
            select_dancer(index) => { root.dancer_settings_select_dancer(index); }
            add_dancer => { root.dancer_settings_add_dancer(); }
            delete_dancer => { root.dancer_settings_delete_dancer(); }
            select_role(index) => { root.dancer_settings_select_role(index); }
            update_dancer_name(value) => { root.dancer_settings_update_dancer_name(value); }
            update_dancer_shortcut(value) => { root.dancer_settings_update_dancer_shortcut(value); }
            update_dancer_color(value) => { root.dancer_settings_update_dancer_color(value); }
            update_swap_from(value) => { root.dancer_settings_update_swap_from(value); }
            update_swap_to(value) => { root.dancer_settings_update_swap_to(value); }
            swap_dancers => { root.dancer_settings_swap(); }
            save => { root.dancer_settings_save(); }
        }
    }
}
