import { MaterialPalette, MaterialText, MaterialTypography, TextButton, Vertical } from "@material";
import { Translations } from "translations.slint";

export component SwapDancersDialogView inherits Rectangle {
    in property <string> title_text: Translations.dancer_swap_dialog_title;
    in property <string> message_text;
    in property <string> confirm_text: Translations.dancer_swap_dialog_confirm;
    in property <string> cancel_text: Translations.dancer_swap_dialog_cancel;
    in property <color> first_color;
    in property <color> second_color;
    in property <string> first_name;
    in property <string> second_name;

    callback confirm();
    callback cancel();

    background: MaterialPalette.surface;
    border-width: 1px;
    border-color: MaterialPalette.outline_variant;
    border-radius: 8px;
    padding: 16px;

    Vertical {
        spacing: 8px;
        MaterialText {
            text: title_text;
            font-size: MaterialTypography.title_large.font_size;
            font-weight: MaterialTypography.title_large.font_weight;
        }
        MaterialText {
            text: first_name;
            font-size: MaterialTypography.body_medium.font_size;
            font-weight: MaterialTypography.body_medium.font_weight;
        }
        MaterialText {
            text: second_name;
            font-size: MaterialTypography.body_medium.font_size;
            font-weight: MaterialTypography.body_medium.font_weight;
        }
        MaterialText {
            text: message_text;
            font-size: MaterialTypography.body_medium.font_size;
            font-weight: MaterialTypography.body_medium.font_weight;
        }
        TextButton { text: cancel_text; clicked => { cancel(); } }
        TextButton { text: confirm_text; clicked => { confirm(); } }
    }
}


