import { IconButton, ListView, MaterialPalette, MaterialText, Vertical, Horizontal } from "@material";
import { SceneItemView } from "scene_item_view.slint";
import { SceneSearchBar } from "scene_search_bar.slint";
import { SceneListItem, ScenesInfo } from "scenes_info.slint";
import { Translations } from "../../ui/translations.slint";

export component ScenesPaneView inherits Rectangle {
    property <[SceneListItem]> scenes: ScenesInfo.scenes;
    property <string> search_text: ScenesInfo.search_text;
    property <bool> show_timestamps: ScenesInfo.show_timestamps;
    property <bool> can_save_choreo: ScenesInfo.can_save_choreo;
    property <bool> can_delete_scene: ScenesInfo.can_delete_scene;
    property <bool> can_navigate_to_settings: ScenesInfo.can_navigate_to_settings;
    property <bool> can_navigate_to_dancer_settings: ScenesInfo.can_navigate_to_dancer_settings;

    background: MaterialPalette.surface;

    content := Vertical {
        width: parent.width;
        height: parent.height;
        padding: 12px;
        spacing: 12px;

        Rectangle {
            background: MaterialPalette.surface_container;
            border-radius: 12px;
            vertical-stretch: 1;

            Vertical {
                width: parent.width;
                height: parent.height;
                padding: 8px;

                ListView {
                    vertical-stretch: 1;
                    for scene[index] in scenes: Rectangle {
                        background: transparent;
                        height: root.show_timestamps ? 62px : 50px;

                        scene_content := SceneItemView {
                            width: parent.width;
                            height: parent.height - 8px;
                            y: 4px;
                            scene_name: scene.name;
                            timestamp_text: scene.timestamp_text;
                            scene_color: scene.color;
                            show_timestamps: root.show_timestamps;
                            is_selected: scene.is_selected;
                            select_scene => { ScenesInfo.select_scene(index); }
                        }
                    }
                }
            }
        }

        SceneSearchBar {
            placeholder_text: Translations.search_placeholder;
            text <=> search_text;
            edited(value) => { ScenesInfo.update_search_text(value); }
        }

        Horizontal {
            spacing: 8px;

            IconButton {
                icon: @image-url("../../ui/icons/TableRowPlusBefore.svg");
                tooltip: Translations.scenes_add_before;
                clicked => { ScenesInfo.add_scene_before(); }
            }
            IconButton {
                icon: @image-url("../../ui/icons/TableRowPlusAfter.svg");
                tooltip: Translations.scenes_add_after;
                clicked => { ScenesInfo.add_scene_after(); }
            }
            IconButton {
                icon: @image-url("../../ui/icons/Delete.svg");
                tooltip: Translations.delete_scene_dialog_title;
                enabled: can_delete_scene;
                clicked => { ScenesInfo.delete_scene(); }
            }
        }

        Horizontal {
            spacing: 8px;
            IconButton {
                icon: @image-url("../../ui/icons/FolderOpen.svg");
                tooltip: Translations.scenes_open;
                clicked => { ScenesInfo.open_choreo(); }
            }
            IconButton {
                icon: @image-url("../../ui/icons/ContentSave.svg");
                tooltip: Translations.scenes_save;
                enabled: can_save_choreo;
                clicked => { ScenesInfo.save_choreo(); }
            }
            IconButton {
                icon: @image-url("../../ui/icons/Cog.svg");
                tooltip: Translations.settings_title;
                enabled: can_navigate_to_settings;
                clicked => { ScenesInfo.navigate_to_settings(); }
            }
            IconButton {
                icon: @image-url("../../ui/icons/AccountGroup.svg");
                tooltip: Translations.dancers_title;
                enabled: can_navigate_to_dancer_settings;
                clicked => { ScenesInfo.navigate_to_dancer_settings(); }
            }
        }
    }
}
